name: first_task
on: 
  workflow_dispatch: 

jobs:
  Tarea1:
    runs-on: ubuntu-latest

    steps:
      - name: Saluda a todos
        run: echo "Welcome a todos"

  Tarea2:
    runs-on: ubuntu-latest

    steps:
      - name: Decir fecha
        run: date
